# Generated by Django 4.1.4 on 2022-12-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menucategories_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategories',
            name='image',
        ),
    ]
